[package]
name = "modules_as_seperate_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "demo"
path = "src/lib.rs" #don't forget the .rs

[dependencies]
